### ISSUE TITLE
Quarkus 2.7.0 Application crash on startup

### ISSUE THREAD

**Issue by computerlove** [quarkiverse/quarkus-vault#21]
Because jndi is disabled by default in Quarkus 2.7.0 our application fails to start when trying to setup the Vault extension.
```
Feb 08, 2022 12:43:55 PM io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider
WARN: Default DNS servers: [/8.8.8.8:53, /8.8.4.4:53] (Google Public DNS as a fallback)
Feb 08, 2022 12:44:06 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile prod)
io.netty.resolver.dns.DnsNameResolverTimeoutException: [/8.8.4.4:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
```
Connecting to the instance with debugger show that `javax.naming.NamingException: JNDI has been disabled, enable it with quarkus.naming.enable-jndi=true` is thrown (and ignored) here: 
```
at io.netty.resolver.dns.DirContextUtils.addNameServers(DirContextUtils.java:49)
at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:53)
at io.vertx.core.impl.resolver.DnsResolverProvider.<init>(DnsResolverProvider.java:77)
at io.vertx.core.spi.resolver.ResolverProvider.factory(ResolverProvider.java:39)
at io.vertx.core.impl.AddressResolver.<init>(AddressResolver.java:76)
at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:180)
at io.vertx.core.impl.VertxBuilder.vertx(VertxBuilder.java:225)
at io.vertx.core.Vertx.vertx(Vertx.java:86)
at io.vertx.core.Vertx.vertx(Vertx.java:76)
at io.vertx.mutiny.core.Vertx.vertx(Vertx.java:116)
at io.quarkus.vault.runtime.client.VertxVaultClient.<init>(VertxVaultClient.java:61)
at io.quarkus.vault.runtime.client.VertxVaultClient_Bean.create(Unknown Source)
at io.quarkus.vault.runtime.client.VertxVaultClient_Bean.create(Unknown Source)
at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:101)
at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
at io.quarkus.vault.runtime.client.VertxVaultClient_Bean.get(Unknown Source)
at io.quarkus.vault.runtime.client.VertxVaultClient_Bean.get(Unknown Source)
at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:428)
at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:441)
at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:412)
at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:229)
at io.quarkus.vault.runtime.VaultRecorder.configure(VaultRecorder.java:36)
at io.quarkus.deployment.steps.VaultProcessor$init1872323611.deploy_0(Unknown Source)
at io.quarkus.deployment.steps.VaultProcessor$init1872323611.deploy(Unknown Source)
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
at io.quarkus.runner.GeneratedMain.main(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

Following the path above I cannot see that it touches any path other than using DirContextUtils.addNameServers.
io.vertx.core.impl.resolver.DnsResolverProvider.<init> has a path where Vert.x' AddressResolverOptions is used, but VertxVaultClientinitializes with Vertx.vertx(), so the relevant options is not possible to set.

([issue discussion on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/jndi.20disabled.20by.20default-.3E.20application.20does.20not.20start))

**Comment by vsevel** [comment]
so what should be done exactly? what option from the `AddressResolverOptions` should we expose in the vault extension?
cc @cescoffier

**Comment by cescoffier** [comment]
Quarkus 2.7 disables jndi, which makes netty uses the Google dns server. However that should not always be the case.

The idea would be to allows passing a list of address servers (dns servers) and configure the vertx instance with it.

So what we will do is to fix that issue in Quarkus core and make the vault extension read the same config property to configure the address resolver.

I will try to have a look tomorrow, and will let you know.

**Comment by cescoffier** [comment]
Of course the workaround is to enable jndi but... well...
