### ISSUE TITLE
Invalid token when use approle authentication

### ISSUE THREAD

**Issue by henryx** [quarkiverse/quarkus-vault#342]
According to the documentation, I've created an approle with these commands:
```
cat <<EOF | vault policy write a_policy -
path "a_mount/a_kv" { capabilities = ["read"]}
EOF

vault auth enable approle
vault write auth/approle/role/a_role token_policies="a_policy" \
    token_ttl=1h token_max_ttl=4h

vault secrets enable -path=a_mount -version=1 kv
vault kv put --mount=a_mount a_kv mongo_pass=test

export ROLE_ID=$(vault read -format=json auth/approle/role/a_role/role-id | jq -r '.data.role_id')
export SECRET_ID=$(vault write -format=json -force auth/approle/role/a_role/secret-id | jq -r '.data.secret_id')

export VAULT_TOKEN=$(vault write -format=json auth/approle/login role_id=$ROLE_ID secret_id=$SECRET_ID | jq -r '.auth.client_token')

vault kv get --mount=a_mount a_kv
======= Data =======
Key           Value
---           -----
mongo_pass    test
```
In my Quarkus application, I've used this configuration:
```
quarkus.mongodb.connection-string=mongodb://admin:${mongo_pass}@localhost:27017
quarkus.mongodb.database=testDB
quarkus.vault.url=http://localhost:8200
quarkus.vault.authentication.app-role.role-id=<a_role>
quarkus.vault.authentication.app-role.secret-id=<a_secret>
quarkus.mongodb.credentials.credentials-provider=a_provider
quarkus.vault.kv-secret-engine-mount-path=a_mount
quarkus.vault.credentials-provider.a_provider.kv-path=a_kv
quarkus.vault.credentials-provider.a_provider.kv-key=mongo_pass
quarkus.vault.kv-secret-engine-version=1
```
But when I start the application, I get this error:
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus

	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:627)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:711)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:241)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:594)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:644)
	... 1 more
Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [h1_G0-d2ADp3y2Tmh2-WKjUlre0]: VaultClientException{operationName='VAULT [SECRETS (kv1)] Read', requestPath='http://localhost:8200/v1/a_mount/a_kv', status=403, errors=[2 errors occurred:
	* permission denied
	* invalid token

]}
	at com.mongodb.client.MongoClient_h1_G0-d2ADp3y2Tmh2-WKjUlre0_Synthetic_Bean.doCreate(Unknown Source)
[...]
```
What I missing?  Quarkus-vault is 4.1.0

**Comment by vsevel** [comment]
hello @henryx . is this still an issue?

**Comment by henryx** [comment]
Hi @vsevel. This ticket is almost two years old, so, at the time, I thinked it was an issue, but I've not investigated much and i've solved in another way. It can be considered it an issue if respond at this question: this plugin can be authenticate via Vault appRole mechanism?

**Comment by vsevel** [comment]
to answer your question directly: **yes, this extension does support AppRole authentication**, and looking at your stack trace, it actually *did* authenticate successfully. Here's the breakdown.

## AppRole is supported

The code path is intact:

- `VaultAppRoleTokenProvider.apply()` calls `auth/approle/login` with your `role-id`/`secret-id` and keeps the returned `client_token`.
- It's covered by an integration test: `integration-tests/vault/.../VaultAppRoleITCase.java`.

## What the trace actually shows

The key detail is the failing operation and path:

```
operationName='VAULT [SECRETS (kv1)] Read', requestPath='http://localhost:8200/v1/a_mount/a_kv', status=403
```

This is the **KV read**, not the login. If the AppRole login had failed, the failing operation would be `VAULT [AUTH (approle)] Login` against `/v1/auth/approle/login`. Since the failure is on the read *that happens after login*, we know:

1. The **AppRole login succeeded** and returned a valid `client_token`.
2. That token was then used for the `kv1` read at `a_mount/a_kv`, and Vault rejected it with `403 permission denied / invalid token`.

Also note the path is `v1/a_mount/a_kv` (no `/data/` segment), which confirms `kv-secret-engine-version=1` took effect correctly — so the mount/version config is fine and the path exactly matches your policy `path "a_mount/a_kv"`.

I am currently going through issues that have not been answered. sorry it has taken so long. 
`approle` is definitely supported, and used extensively in the test suite.

I am glad you found a workaround. to make it faster for resolution, please post a reproducer if you find an issue in the future.
